// server/store/live_projects.go — CRUD for the live_projects table.
//
// A live project is a server-side record that holds a unique ID and a
// human-friendly name. The ID is used in webhook URLs and WebSocket channels.
// The name is displayed in the IDE Settings dialog.
//
// Projects are owned by a user and follow them across machines — no
// localStorage dependency.
//
// Português:
//
//	CRUD para live_projects. O ID único é usado em URLs de webhook e
//	canais WebSocket. O nome é exibido no Settings. Acompanha o usuário
//	entre máquinas — sem depender de localStorage.
package store

import (
	"database/sql"
	"errors"
	"fmt"
	"time"
)

// LiveProject represents a live communication project.
type LiveProject struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

// CreateLiveProject inserts a new live project.
// The ID must be pre-generated by the caller (cryptoauth.MustNewID()).
func CreateLiveProject(p *LiveProject) error {
	_, err := DB.Exec(`
		INSERT INTO live_projects (id, user_id, name, created_at)
		VALUES (?, ?, ?, ?)`,
		p.ID, p.UserID, p.Name, p.CreatedAt,
	)
	return err
}

// GetLiveProject returns a single project by ID, scoped to the user.
func GetLiveProject(userID, projectID string) (*LiveProject, error) {
	var p LiveProject
	err := DB.QueryRow(`
		SELECT id, user_id, name, created_at
		FROM live_projects
		WHERE id = ? AND user_id = ?`,
		projectID, userID,
	).Scan(&p.ID, &p.UserID, &p.Name, &p.CreatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("store: get live project: %w", err)
	}
	return &p, nil
}

// ListLiveProjects returns all live projects for a user, newest first.
func ListLiveProjects(userID string) ([]LiveProject, error) {
	rows, err := DB.Query(`
		SELECT id, user_id, name, created_at
		FROM live_projects
		WHERE user_id = ?
		ORDER BY created_at DESC`,
		userID,
	)
	if err != nil {
		return nil, fmt.Errorf("store: list live projects: %w", err)
	}
	defer rows.Close()

	var projects []LiveProject
	for rows.Next() {
		var p LiveProject
		if err := rows.Scan(&p.ID, &p.UserID, &p.Name, &p.CreatedAt); err != nil {
			return nil, fmt.Errorf("store: scan live project: %w", err)
		}
		projects = append(projects, p)
	}
	return projects, rows.Err()
}

// UpdateLiveProjectName updates the name of an existing project.
func UpdateLiveProjectName(userID, projectID, name string) error {
	result, err := DB.Exec(`
		UPDATE live_projects SET name = ?
		WHERE id = ? AND user_id = ?`,
		name, projectID, userID,
	)
	if err != nil {
		return fmt.Errorf("store: update live project: %w", err)
	}
	n, _ := result.RowsAffected()
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// DeleteLiveProject removes a project and cascading API keys should be
// handled by the caller (or by adding a FK on api_keys.project_id).
func DeleteLiveProject(userID, projectID string) error {
	result, err := DB.Exec(`
		DELETE FROM live_projects WHERE id = ? AND user_id = ?`,
		projectID, userID,
	)
	if err != nil {
		return fmt.Errorf("store: delete live project: %w", err)
	}
	n, _ := result.RowsAffected()
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// EnsureLiveProject returns an existing project or creates a new one.
// Used by the Settings dialog: the user types a name, and the server either
// finds it or creates it with a fresh unique ID.
func EnsureLiveProject(userID, name string) (*LiveProject, bool, error) {
	// Try to find existing by name.
	var p LiveProject
	err := DB.QueryRow(`
		SELECT id, user_id, name, created_at
		FROM live_projects
		WHERE user_id = ? AND name = ?`,
		userID, name,
	).Scan(&p.ID, &p.UserID, &p.Name, &p.CreatedAt)

	if err == nil {
		return &p, false, nil // found existing
	}
	if !errors.Is(err, sql.ErrNoRows) {
		return nil, false, fmt.Errorf("store: ensure live project: %w", err)
	}

	// Create new.
	now := time.Now().UTC().Format(time.RFC3339)
	p = LiveProject{
		UserID:    userID,
		Name:      name,
		CreatedAt: now,
	}
	// ID is set by the caller after calling this function.
	return &p, true, nil
}
