// server/tasks/codegen.go — Asynq task definition for asynchronous code generation.
//
// Task type:
//
//	codegen:run — run the codegen pipeline (SceneJSON → graph → IR → backend)
//	              against the scene submitted by the IDE and publish the
//	              resulting source code (plus diagnostics) back to Redis so
//	              the SSE stream handler can deliver it to the WASM client.
//
// Result storage:
//
//	Three Redis keys per job, all with the same TTL:
//	  codegen:job:{jobID}:state    — string: "queued" | "running" | "done" | "failed"
//	  codegen:job:{jobID}:result   — JSON of codegen.Response (only when state="done")
//	  codegen:job:{jobID}:error    — plain text (only when state="failed", infra-level)
//	  codegen:job:{jobID}:language — string, written by the submit handler, used by
//	                                 the status endpoint to echo the language back.
//
//	"done" means the pipeline finished AND its Response was serialised. A
//	Response that contains semantic errors (geometric conflicts, missing
//	black-box defs, etc.) is still a "done" state — those errors are part of
//	the payload the client expects. "failed" is reserved for infrastructure
//	problems: panic in Generate, context timeout from Asynq, marshal error.
//
// Queue and retry policy:
//
//	Codegen is interactive — the maker clicked "Export → Go Code" and is
//	staring at a spinner. It runs on a dedicated "codegen" queue with the
//	highest weight (see cmd/worker/main.go).
//
//	MaxRetry is 0: codegen is deterministic, so retrying a failure simply
//	produces the same failure. A failed job surfaces to the user once and
//	the user decides whether to fix the scene and resubmit.
//
//	Timeout is 120s, matching the device:github precedent. The Generate
//	pipeline is pure CPU — no network, no disk — so this is a runaway
//	guard rather than an expected ceiling. Most jobs complete in <2s.
//
// Português:
//
//	Definição de tarefa Asynq para geração de código assíncrona. Resultado
//	publicado em três chaves no Redis. Fila dedicada "codegen" com peso
//	alto (usuário esperando). Sem retry porque codegen é determinístico.
//	Timeout de 120s funciona como freio contra runaway, não como expectativa
//	de tempo normal de execução.
package tasks

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/hibiken/asynq"
)

const (
	// TypeCodegenRun is the task type for running the code generation pipeline.
	TypeCodegenRun = "codegen:run"

	// QueueCodegen is the Asynq queue name for codegen tasks. It is registered
	// with the highest weight in cmd/worker/main.go because codegen is
	// interactive — the user is actively waiting for the result.
	QueueCodegen = "codegen"

	// CodegenJobTTL is how long all codegen:job:{id}:* keys live in Redis.
	// 10 minutes matches the previous synchronous flow and gives the SSE
	// stream handler ample time to deliver the result, including the case
	// where the EventSource disconnects (proxy timeout) and the browser
	// reconnects mid-job. Exported so the handler package can use the same
	// constant for the language key it writes at submit time.
	CodegenJobTTL = 10 * time.Minute
)

// CodegenPayload carries everything the worker needs to run the codegen
// pipeline. The submit handler builds this from the HTTP request, marshals
// it as the task payload, and enqueues the task. The worker unmarshals it
// and feeds the fields straight into codegen.Request.
//
// BlackBoxDefs is serialised as json.RawMessage to keep this package free
// of dependencies on server/codegen/blackbox (which would pull the AST
// parser into every binary that imports tasks). The worker unmarshals the
// raw bytes into map[string]*blackbox.BlackBoxDef when it builds the
// codegen.Request.
//
// All field tags use camelCase per the project-wide invariant that Go
// structs serving JSON to JS/WASM must declare explicit lower-camelCase
// tags. Even though this payload is server-only today, keeping the
// convention costs nothing and protects against the day someone
// inadvertently exposes a payload field through an admin endpoint.
//
// Português:
//
//	Carrega tudo que o worker precisa para rodar o codegen. BlackBoxDefs
//	vem serializado como json.RawMessage para evitar dependência
//	circular entre os packages tasks e codegen/blackbox.
type CodegenPayload struct {
	// JobID is the Redis key suffix for publishing state and result.
	// Generated by the submit handler before enqueueing.
	JobID string `json:"jobId"`

	// Language is the target language identifier: "go", "c", "python", ...
	// Passed through to codegen.Request.Language. The current backend only
	// supports "go"; other values trigger a SeverityError diagnostic inside
	// Generate, which is still considered a "done" state.
	Language string `json:"language"`

	// Scene is the SceneJSON exported by the IDE (SceneMgr.Export()).
	// Stored as raw bytes so Asynq does not deserialise/reserialise it
	// during transit and the worker hands it straight to graph.Build.
	Scene json.RawMessage `json:"scene"`

	// BlackBoxDefs is a JSON object mapping struct name → BlackBoxDef.
	// Empty (nil or "null") when the scene contains no black-box devices.
	//
	// Loaded by the submit handler via store.LoadBlackBoxDefsForScene and
	// serialised here so the worker does not need direct DB access for
	// codegen — only the worker process that handles GitHub uploads needs
	// the store package for that purpose.
	BlackBoxDefs json.RawMessage `json:"blackBoxDefs,omitempty"`

	// PreviewCase, when non-nil, switches the worker from a full scene
	// generation to a StatementCase inspect-panel preview: the worker calls
	// codegen.PreviewCase against these draft cases instead of running
	// codegen.Generate against Scene. Scene and BlackBoxDefs are empty in
	// that mode. It is carried through the SAME task type and the SAME result
	// channel so the preview rides the existing async transport (codegen
	// queue, Redis result keys, SSE delivery) with no parallel path.
	//
	// Português: Quando não-nil, troca a geração de cena cheia por um preview
	// de StatementCase do painel — o worker chama codegen.PreviewCase com
	// estes cases em rascunho em vez do Generate. Mesma task, mesmo canal de
	// resultado, sem caminho paralelo.
	PreviewCase *CasePreviewInput `json:"previewCase,omitempty"`
}

// CasePreviewInput carries a draft StatementCase for the inspect-panel
// preview. The submit handler fills it from the panel's unsaved cases; the
// worker unmarshals Cases into []graph.CaseDef and calls codegen.PreviewCase.
//
// Cases is json.RawMessage for the same reason BlackBoxDefs is: it keeps the
// tasks package free of a dependency on server/codegen/graph. The worker —
// which already imports the codegen packages — unmarshals it.
//
// The target language is NOT here: it travels on CodegenPayload.Language (the
// :language path param), shared with the full-generation flow.
//
// Português: Carrega um StatementCase em rascunho para o preview do painel.
// Cases vai como json.RawMessage para manter o package tasks sem dependência
// de server/codegen/graph. A linguagem viaja em CodegenPayload.Language.
type CasePreviewInput struct {
	// ScopeID is the StatementCase device ID, echoed onto the diagnostics so
	// the panel can attribute them.
	ScopeID string `json:"scopeId"`

	// SelectorType distinguishes a bool selector (no cross-case diagnostics)
	// from an integer selector. Comes from the connected wire's type.
	SelectorType string `json:"selectorType"`

	// Cases is the JSON array of the device's ordered cases, unmarshalled by
	// the worker into []graph.CaseDef.
	Cases json.RawMessage `json:"cases"`
}

// NewCodegenRunTask constructs an Asynq task for the codegen pipeline.
//
// The returned task carries:
//   - asynq.Queue(QueueCodegen)   — dedicated interactive queue
//   - asynq.MaxRetry(0)           — codegen is deterministic, no retries
//   - asynq.Timeout(120s)         — runaway guard
//   - asynq.Retention(5 minutes)  — keep the task record around briefly
//     after completion so the Asynq web inspector can show it; the actual
//     result lives in Redis under codegen:job:{id}:result with its own TTL.
//
// The caller is responsible for having already populated
// codegen:job:{JobID}:state = "queued" in Redis before enqueueing, so a
// fast EventSource reconnect always finds a known state rather than the
// ambiguous "unknown" reply from the status endpoint.
func NewCodegenRunTask(p CodegenPayload) (*asynq.Task, error) {
	b, err := json.Marshal(p)
	if err != nil {
		return nil, fmt.Errorf("tasks: marshal codegen payload: %w", err)
	}
	return asynq.NewTask(TypeCodegenRun, b,
		asynq.Queue(QueueCodegen),
		asynq.MaxRetry(0),
		asynq.Timeout(120*time.Second),
		asynq.Retention(5*time.Minute),
	), nil
}
