// /server/codegen/backend/ansic/ident_test.go
// SPDX-FileCopyrightText: 2026 Helmut Kemper
// SPDX-License-Identifier: AGPL-3.0-only

package ansic

// ident_test.go — Unit tests for the pure string helpers in ident.go.
//
// All tests are table-driven where the input space is large enough to
// benefit, and direct otherwise. Each function is exercised against
// the cases the design document calls out plus a small set of
// adversarial inputs (empty strings, leading digits, multiple
// underscore-digit boundaries, unicode garbage).
//
// Where the test pins a behaviour that is intentionally lenient or
// "Phase 2 TODO" (e.g. cIdent does not escape keywords), the test
// asserts the lenient behaviour and a comment marks why — so when
// hardening lands, the test will need to be updated alongside the
// implementation, deliberately.
//
// Português:
//
//	Testes unitários puros para os helpers de ident.go. Casos
//	tabulados onde faz sentido, com edge cases adversariais. Onde
//	o comportamento atual é deliberadamente lento (não escapa
//	keywords, não checa primeiro caractere), o teste pina esse
//	comportamento com um comentário marcando o futuro hardening.

import "testing"

// =====================================================================
//  cIdent
// =====================================================================

func TestCIdent(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		// Bread-and-butter cases — device IDs as generated by the IoTMaker IDE.
		{"const_int_ide_style", "constInt_1", "constInt1"},
		{"add_ide_style", "add_2", "add2"},
		{"i2c_bus_ide_style", "i2cBus_42", "i2cBus42"},
		{"loop_ide_style", "stmLoop_1", "stmLoop1"},

		// Empty input defaults to "v" — defensive guard, never
		// expected to fire in practice. Matches goIdent.
		{"empty_string_collapses_to_v", "", "v"},

		// No transformation needed.
		{"identity_no_underscores", "alreadyClean", "alreadyClean"},
		{"identity_just_letters", "abc", "abc"},

		// Underscores that don't precede a digit are kept (they are
		// valid C identifier characters and the IoTMaker IDE may
		// use them in custom device names).
		{"underscore_followed_by_letter_kept", "foo_bar", "foo_bar"},
		{"trailing_underscore_kept", "foo_", "foo_"},

		// Multiple underscore-digit boundaries.
		{"two_underscore_digit_groups", "foo_1_bar_2", "foo1_bar2"},

		// Underscore at the very start, followed by digit, is
		// stripped — exposes a leading digit. This is the Phase 2
		// hardening gotcha noted in ident.go. The test pins the
		// current (lenient) behaviour to make any future change
		// explicit.
		{"leading_underscore_digit_strips_to_invalid", "_1foo", "1foo"},

		// Multi-byte characters survive (the byte-level loop only
		// inspects digits and the underscore, both single-byte).
		{"unicode_pass_through", "fóo_1", "fóo1"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := cIdent(tc.in)
			if got != tc.want {
				t.Errorf("cIdent(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

// =====================================================================
//  cOperand
// =====================================================================

func TestCOperand(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		// Simple register references — strip the '%' and apply
		// cIdent's underscore-before-digit rule.
		{"simple_ref", "%constInt_1", "constInt1"},
		{"simple_ref_no_underscore", "%alreadyClean", "alreadyClean"},

		// Compound references (Phase 2 black-box outputs). Two
		// halves: instance ID gets cIdent'd; port name is appended
		// verbatim with an underscore separator. Matches goOperand
		// so paired Go/C output reads identically when debugging.
		{"compound_ref", "%i2cBus_1:bus", "i2cBus1_bus"},
		{"compound_ref_no_underscore_in_instance", "%clock:tick", "clock_tick"},

		// Literals (no '%' prefix) pass through unchanged — they
		// may be string constants like the OUTPUT channel name, or
		// numeric values that bypassed the CONST → register path.
		{"literal_passthrough_number", "42", "42"},
		{"literal_passthrough_string", `"hello"`, `"hello"`},
		{"literal_passthrough_negative", "-3.14", "-3.14"},

		// Edge cases.
		{"empty_string_passes_through", "", ""},
		{"only_percent_collapses_to_v", "%", "v"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := cOperand(tc.in)
			if got != tc.want {
				t.Errorf("cOperand(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

// =====================================================================
//  cTypeName
// =====================================================================

// TestCTypeName_AbstractTypes_RespectsProfile walks every abstract IR
// type through every shipped profile, asserting the concrete C type
// reflects the profile's IntType / FloatType / BoolType choices.
func TestCTypeName_AbstractTypes_RespectsProfile(t *testing.T) {
	profiles := ListProfiles()

	for _, p := range profiles {
		p := p
		t.Run(p.Name, func(t *testing.T) {
			if got := cTypeName("int", p); got != p.IntType {
				t.Errorf("cTypeName(\"int\", %s) = %q, want %q",
					p.Name, got, p.IntType)
			}
			if got := cTypeName("float", p); got != p.FloatType {
				t.Errorf("cTypeName(\"float\", %s) = %q, want %q",
					p.Name, got, p.FloatType)
			}
			if got := cTypeName("bool", p); got != p.BoolType {
				t.Errorf("cTypeName(\"bool\", %s) = %q, want %q",
					p.Name, got, p.BoolType)
			}
		})
	}
}

// TestCTypeName_StringMapsToConstCharPtr pins the "string" mapping.
// Phase 1 doesn't exercise it, but the mapping is fixed by design.
func TestCTypeName_StringMapsToConstCharPtr(t *testing.T) {
	for _, p := range ListProfiles() {
		got := cTypeName("string", p)
		want := "const char*"
		if got != want {
			t.Errorf("cTypeName(\"string\", %s) = %q, want %q",
				p.Name, got, want)
		}
	}
}

// TestCTypeName_TimeDurationIsAlwaysInt64 pins the deliberate
// non-profile-dependent mapping of time.Duration. The Go IR carries
// duration values as Go's time.Duration alias, which is always
// int64. In C the same representation is int64_t, regardless of the
// profile's default IntType. Picking int32_t on arduino_uno would
// overflow at one-second cadence (10^9 ns > INT32_MAX).
func TestCTypeName_TimeDurationIsAlwaysInt64(t *testing.T) {
	for _, p := range ListProfiles() {
		got := cTypeName("time.Duration", p)
		want := "int64_t"
		if got != want {
			t.Errorf("cTypeName(\"time.Duration\", %s) = %q, want %q (unconditional int64_t)",
				p.Name, got, want)
		}
	}
}

// TestCTypeName_EmptyDefaultsToIntType is the defensive fallback for
// emitters that forgot to set inst.Type. Matches goTypeName's "int64"
// default but follows the profile here.
func TestCTypeName_EmptyDefaultsToIntType(t *testing.T) {
	p := ResolveProfile(ProfileNameArduinoUno)
	if got := cTypeName("", p); got != p.IntType {
		t.Errorf("cTypeName(\"\", arduino_uno) = %q, want %q (= IntType)",
			got, p.IntType)
	}
}

// TestCTypeName_UnknownPassThrough covers the GENUINE pass-through
// territory: pointer/struct tokens from black-box parsers
// (*machine.I2C, sht3x_t*) keep their authored spelling so they reach
// the C compiler verbatim. The FIXED-WIDTH integer tokens used to sit
// here as Phase-2 debt; since T7 of the const-array plan they are
// translated (see TestCTypeName_FixedWidthIntegers below), so this
// test now pins only what must remain untranslated.
func TestCTypeName_UnknownPassThrough(t *testing.T) {
	p := ResolveProfile(ProfileNameArduinoUno)
	cases := []string{"*machine.I2C", "sht3x_t*", "esp_err_t"}
	for _, in := range cases {
		if got := cTypeName(in, p); got != in {
			t.Errorf("cTypeName(%q, arduino_uno) = %q, want %q (passthrough)",
				in, got, in)
		}
	}
}

// TestCTypeName_FixedWidthIntegers pins the T7 translation: fixed-width
// IDE tokens (the element types collection inference produces, and any
// authored Go scalar) map to their <stdint.h> C names — stdint is one of
// the foundational includes, so the names are always available. "byte"
// is Go's alias of uint8 and shares its C face.
func TestCTypeName_FixedWidthIntegers(t *testing.T) {
	p := ResolveProfile(ProfileNameArduinoUno)
	cases := map[string]string{
		"int8": "int8_t", "int16": "int16_t",
		"int32": "int32_t", "int64": "int64_t",
		"uint8": "uint8_t", "uint16": "uint16_t",
		"uint32": "uint32_t", "uint64": "uint64_t",
		"byte": "uint8_t",
	}
	for in, want := range cases {
		if got := cTypeName(in, p); got != want {
			t.Errorf("cTypeName(%q, arduino_uno) = %q, want %q", in, got, want)
		}
	}
}

// TestCLiteral_FixedWidthSuffixes pins the per-width literal suffixes
// (T7): narrow widths need none (a C99 decimal literal is already an
// int — §6.4.4.1); 32/64-bit signed mirror the profile ladder (L / LL);
// unsigned add U because decimal literals never become unsigned on
// their own, and values above INT64_MAX REQUIRE the ULL to be legal at
// all.
func TestCLiteral_FixedWidthSuffixes(t *testing.T) {
	p := ResolveProfile(ProfileNameArduinoUno)
	cases := []struct{ typ, val, want string }{
		{"int8", "5", "5"},
		{"int16", "5", "5"},
		{"uint8", "5", "5"},
		{"uint16", "5", "5"},
		{"byte", "5", "5"},
		{"int32", "5", "5L"},
		{"int64", "5", "5LL"},
		{"uint32", "5", "5UL"},
		{"uint64", "5", "5ULL"},
	}
	for _, c := range cases {
		if got := cLiteral(c.typ, c.val, p); got != c.want {
			t.Errorf("cLiteral(%q, %q) = %q, want %q", c.typ, c.val, got, c.want)
		}
	}
}

// TestCTypeName_ConcreteFloatPrecision pins the concrete float types a
// StatementConstFloat device emits. Unlike the abstract "float" (which
// follows the profile's FloatType), float32/float64 carry the maker's
// explicit precision choice and map to standard C "float"/"double" in
// EVERY profile — the choice is the maker's, not the target's.
func TestCTypeName_ConcreteFloatPrecision(t *testing.T) {
	cases := []struct {
		irType string
		want   string
	}{
		{"float32", "float"},
		{"float64", "double"},
	}
	for _, p := range ListProfiles() {
		for _, tc := range cases {
			if got := cTypeName(tc.irType, p); got != tc.want {
				t.Errorf("cTypeName(%q, %s) = %q, want %q (profile-independent)",
					tc.irType, p.Name, got, tc.want)
			}
		}
	}
}

// =====================================================================
//  cLiteral
// =====================================================================

// TestCLiteral_Int exhaustively maps integer literals across all
// profiles. The suffix from the profile must be appended; negative
// signs survive untouched.
func TestCLiteral_Int(t *testing.T) {
	cases := []struct {
		profile string
		val     string
		want    string
	}{
		{ProfileNameArduinoUno, "10", "10L"},
		{ProfileNameArduinoUno, "0", "0L"},
		{ProfileNameArduinoUno, "-42", "-42L"},
		{ProfileNameArduinoUno, "2147483647", "2147483647L"}, // INT32_MAX
		{ProfileNameCortexM, "10", "10L"},
		{ProfileNamePiLinux, "10", "10LL"},
		{ProfileNamePiLinux, "-42", "-42LL"},
		{ProfileNamePortable, "10", "10L"},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.profile+"_"+tc.val, func(t *testing.T) {
			p := ResolveProfile(tc.profile)
			if got := cLiteral("int", tc.val, p); got != tc.want {
				t.Errorf("cLiteral(\"int\", %q, %s) = %q, want %q",
					tc.val, tc.profile, got, tc.want)
			}
		})
	}
}

// TestCLiteral_Float covers the suffix and the ".0 insertion" gotcha.
// Critical case: a bare integer like "3" passed as a float must
// become "3.0f" (not "3f", which is invalid C).
func TestCLiteral_Float(t *testing.T) {
	cases := []struct {
		profile string
		val     string
		want    string
	}{
		// With decimal point — suffix appends directly.
		{ProfileNameArduinoUno, "3.14", "3.14f"},
		{ProfileNamePiLinux, "3.14", "3.14"}, // empty FloatSuffix

		// Negative.
		{ProfileNameArduinoUno, "-3.14", "-3.14f"},
		{ProfileNamePiLinux, "-3.14", "-3.14"},

		// Exponent counts as "looks like float" — no .0 needed.
		{ProfileNameArduinoUno, "1e10", "1e10f"},
		{ProfileNameArduinoUno, "1.5E-3", "1.5E-3f"},
		{ProfileNamePiLinux, "1e10", "1e10"},

		// The critical case: bare integer used as a float. The C
		// lexer would reject "3f" outright, so we insert ".0"
		// before the suffix.
		{ProfileNameArduinoUno, "3", "3.0f"},
		{ProfileNameArduinoUno, "-7", "-7.0f"},
		{ProfileNamePiLinux, "3", "3.0"}, // also needs ".0" to be a float in C

		// Zero is the same edge.
		{ProfileNameArduinoUno, "0", "0.0f"},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.profile+"_"+tc.val, func(t *testing.T) {
			p := ResolveProfile(tc.profile)
			if got := cLiteral("float", tc.val, p); got != tc.want {
				t.Errorf("cLiteral(\"float\", %q, %s) = %q, want %q",
					tc.val, tc.profile, got, tc.want)
			}
		})
	}
}

// TestCLiteral_ConcreteFloatPrecision covers the literal rendering for a
// StatementConstFloat's explicit precision. float32 gets an unconditional
// "f" suffix (so the literal is a float, not a double the compiler must
// narrow); float64 gets none (an unsuffixed C floating literal is already
// a double). Both share the ".0 insertion" gotcha — a bare integer must
// gain a decimal point or the C lexer rejects it. All profile-independent:
// the precision is the maker's choice, so profile.FloatSuffix is ignored.
func TestCLiteral_ConcreteFloatPrecision(t *testing.T) {
	cases := []struct {
		irType string
		val    string
		want   string
	}{
		// float32 → unconditional "f" suffix.
		{"float32", "3.14", "3.14f"},
		{"float32", "-2.5", "-2.5f"},
		{"float32", "3", "3.0f"}, // bare int gains ".0"
		{"float32", "0", "0.0f"},
		{"float32", "1e10", "1e10f"}, // exponent already looks like float

		// float64 → no suffix (already a double in C).
		{"float64", "3.14", "3.14"},
		{"float64", "-2.5", "-2.5"},
		{"float64", "3", "3.0"}, // bare int gains ".0"
		{"float64", "0", "0.0"},
		{"float64", "1e10", "1e10"},
	}
	// Two profiles with opposite abstract-float suffixes (arduino_uno
	// appends "f", pi_linux appends nothing) prove the concrete cases
	// ignore profile.FloatSuffix entirely.
	for _, profile := range []string{ProfileNameArduinoUno, ProfileNamePiLinux} {
		p := ResolveProfile(profile)
		for _, tc := range cases {
			if got := cLiteral(tc.irType, tc.val, p); got != tc.want {
				t.Errorf("cLiteral(%q, %q, %s) = %q, want %q (profile-independent)",
					tc.irType, tc.val, profile, got, tc.want)
			}
		}
	}
}

// TestCLiteral_BoolAndStringPassThrough — these IR types arrive
// already in their C-compatible form (true/false from <stdbool.h>,
// quoted strings). The function should be the identity here.
func TestCLiteral_BoolAndStringPassThrough(t *testing.T) {
	p := ResolveProfile(ProfileNameArduinoUno)

	for _, val := range []string{"true", "false"} {
		if got := cLiteral("bool", val, p); got != val {
			t.Errorf("cLiteral(\"bool\", %q) = %q, want %q (identity)",
				val, got, val)
		}
	}

	for _, val := range []string{`"hello"`, `""`, `"with spaces"`} {
		if got := cLiteral("string", val, p); got != val {
			t.Errorf("cLiteral(\"string\", %q) = %q, want %q (identity)",
				val, got, val)
		}
	}
}

// TestCLiteral_TimeDurationAlwaysLL pins the unconditional "LL"
// suffix for duration literals. Unlike int literals (which use the
// profile's IntSuffix — "L" for arduino_uno, "LL" for pi_linux),
// duration is always 64-bit because nanosecond values overflow
// int32 quickly. Using the profile's "L" on arduino_uno would
// truncate the literal at compile time and produce wrong sleep
// durations at runtime — silently. The LL suffix is enforced here
// regardless of profile.
func TestCLiteral_TimeDurationAlwaysLL(t *testing.T) {
	cases := []struct {
		profile string
		val     string
		want    string
	}{
		{ProfileNameArduinoUno, "1000000000", "1000000000LL"}, // 1 sec
		{ProfileNameArduinoUno, "100", "100LL"},
		{ProfileNameCortexM, "1000000000", "1000000000LL"},
		{ProfileNamePiLinux, "1000000000", "1000000000LL"}, // same as int64 here
		{ProfileNamePortable, "500000", "500000LL"},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.profile+"_"+tc.val, func(t *testing.T) {
			p := ResolveProfile(tc.profile)
			if got := cLiteral("time.Duration", tc.val, p); got != tc.want {
				t.Errorf("cLiteral(\"time.Duration\", %q, %s) = %q, want %q (LL unconditional)",
					tc.val, tc.profile, got, tc.want)
			}
		})
	}
}

// TestCLiteral_EmptyTypeTreatedAsInt — same defensive fallback as
// cTypeName: an emitter that forgot to set inst.Type still produces
// a well-formed integer literal rather than a malformed one.
func TestCLiteral_EmptyTypeTreatedAsInt(t *testing.T) {
	p := ResolveProfile(ProfileNameArduinoUno)
	got := cLiteral("", "42", p)
	want := "42L" // same as cLiteral("int", "42", arduino_uno)
	if got != want {
		t.Errorf("cLiteral(\"\", \"42\", arduino_uno) = %q, want %q", got, want)
	}
}

// TestCLiteral_UnknownTypePassThrough — Phase 2 territory; identity
// is the safe default, matching goLiteral.
func TestCLiteral_UnknownTypePassThrough(t *testing.T) {
	p := ResolveProfile(ProfileNameArduinoUno)
	got := cLiteral("uint16", "42", p)
	if got != "42" {
		t.Errorf("cLiteral(\"uint16\", \"42\") = %q, want %q (passthrough)",
			got, "42")
	}
}

// =====================================================================
//  looksLikeFloat (internal helper, tested indirectly above but worth
//  a few direct cases for documentation)
// =====================================================================

func TestLooksLikeFloat(t *testing.T) {
	cases := []struct {
		in   string
		want bool
	}{
		// Decimal point makes it a float.
		{"3.14", true},
		{".5", true},
		{"3.", true},

		// Exponent markers (lowercase and uppercase) make it a float.
		{"1e10", true},
		{"1E10", true},
		{"1.5e-3", true},

		// No decimal, no exponent — looks like int.
		{"3", false},
		{"-42", false},
		{"0", false},
		{"", false},
	}

	for _, tc := range cases {
		t.Run(tc.in, func(t *testing.T) {
			if got := looksLikeFloat(tc.in); got != tc.want {
				t.Errorf("looksLikeFloat(%q) = %v, want %v", tc.in, got, tc.want)
			}
		})
	}
}
