// server/codegen/blackbox/asset_header.go
//
// SPDX-FileCopyrightText: 2026 Helmut Kemper
// SPDX-License-Identifier: AGPL-3.0-only

package blackbox

// asset_header.go — The xxd-style companion-header renderer for the
// unified asset model (docs/tasks/ASSETS_UNIFIED_MODEL.md). It LIVES
// here — the pure, store-free leaf — because BOTH consumers need it:
// the specialist export (projectexport, which forwards to these) and
// the maker's ANSI C emitter (codegen/backend/ansic). Importing
// projectexport from the emitter would drag `store` into codegen and
// break the offline-compilable, database-free codegen layer.
//
// The naming contract is the feature: the specialist hand-writes the
// #include and the symbol BEFORE any export exists —
//
//     templates/logo.gif → templates/logo_gif_data.h
//                          asset_templates_logo_gif[] / _len
//
// Português: O renderer de headers de asset MORA aqui — folha pura,
// sem store — porque os dois consumidores precisam dele: o export do
// especialista (projectexport encaminha) e o emissor C do maker.
// Importar projectexport do emissor arrastaria `store` para o codegen
// e quebraria a camada compilável offline. O contrato de nomes É a
// feature: o especialista escreve include e símbolo À MÃO antes do
// export existir.

import (
	"fmt"
	"strings"
)

// assetSymbolBase converts an authored asset path into the C identifier
// stem shared by the array, its _len companion and the include guard:
// lowercase, every non-alphanumeric byte folded to '_', prefixed with
// "asset_". Path-derived (not basename-derived) so templates/logo.gif
// and img/logo.gif never collide.
//
// Português: Converte o caminho autoral no radical C compartilhado por
// array, _len e guard: minúsculas, todo não-alfanumérico vira '_',
// prefixo "asset_". Derivado do CAMINHO (não do basename) — dois
// logo.gif em pastas diferentes nunca colidem.
func assetSymbolBase(assetPath string) string {
	var b strings.Builder
	b.WriteString("asset_")
	for _, r := range strings.ToLower(assetPath) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

// AssetHeaderPath is the generated header's ZIP path for a given asset:
// same directory, basename's dots folded to '_', suffixed "_data.h" —
// so `templates/logo.gif` yields `templates/logo_gif_data.h` and the
// specialist's relative #include resolves without -I gymnastics.
//
// Português: O caminho do header gerado: mesma pasta, pontos do nome
// viram '_', sufixo "_data.h" — o #include relativo resolve sem -I.
func AssetHeaderPath(assetPath string) string {
	dir := ""
	base := assetPath
	if i := strings.LastIndex(assetPath, "/"); i >= 0 {
		dir, base = assetPath[:i+1], assetPath[i+1:]
	}
	return dir + strings.ReplaceAll(base, ".", "_") + "_data.h"
}

// RenderAssetHeader renders the companion header for one asset's bytes:
// include guard, provenance comment, the byte array (12 per line, the
// xxd -i convention — familiar diffs for embedded folk) and the _len
// companion. `data` is the DECODED payload — the caller owns the
// base64 edge, this renderer owns only bytes.
//
// Português: Renderiza o header do asset: guard, comentário de
// proveniência, o array (12 bytes por linha, convenção do xxd -i) e o
// _len. `data` já vem DECODIFICADO — a borda base64 é do chamador.
func RenderAssetHeader(assetPath string, data []byte) []byte {
	sym := assetSymbolBase(assetPath)
	guard := strings.ToUpper(sym) + "_DATA_H"

	var b strings.Builder
	fmt.Fprintf(&b, "/* Generated by IoTMaker from %s — do not edit.\n", assetPath)
	b.WriteString(" *\n")
	b.WriteString(" * The asset's bytes as a flash-resident array (xxd -i style).\n")
	b.WriteString(" * Include this header and use the symbols below; regeneration\n")
	b.WriteString(" * happens on every export, so edits here are always lost.\n")
	b.WriteString(" *\n")
	fmt.Fprintf(&b, " * Português: Gerado pelo IoTMaker de %s — não edite.\n", assetPath)
	b.WriteString(" * Os bytes do asset como array em flash; regenerado a cada\n")
	b.WriteString(" * export, edições aqui sempre se perdem.\n")
	b.WriteString(" */\n")
	fmt.Fprintf(&b, "#ifndef %s\n#define %s\n\n", guard, guard)
	// AVR flash placement — the compiler decides, not the export: on AVR,
	// `const` alone lands the array in SRAM (2 KB on an Uno; a 12 KB
	// asset cannot even exist there). PROGMEM keeps it in flash, but then
	// direct indexing reads the wrong address space — hence the portable
	// accessor. Every target compiles the SAME header: ASSET attribute
	// empties out and the accessor becomes plain indexing everywhere
	// else. The block is #ifndef-guarded because every asset header of a
	// box repeats it (multi-include safe, identical definitions).
	// Contract for specialists: read bytes via iotm_asset_read(arr, i) —
	// direct arr[i] works on every target EXCEPT AVR.
	// Português: Colocação em flash no AVR — o compilador decide, não o
	// export: no AVR, `const` sozinho põe o array na SRAM (2 KB num Uno).
	// PROGMEM o mantém na flash, mas aí indexação direta lê o espaço de
	// endereço errado — daí o acessor portável. Todo alvo compila o MESMO
	// header. Bloco com guarda #ifndef porque cada header de asset o
	// repete. Contrato para especialistas: leia bytes via
	// iotm_asset_read(arr, i) — arr[i] direto funciona em todo alvo
	// EXCETO AVR.
	b.WriteString("#ifndef IOTM_ASSET_HELPERS\n")
	b.WriteString("#define IOTM_ASSET_HELPERS\n")
	b.WriteString("#ifdef __AVR__\n")
	b.WriteString("#include <avr/pgmspace.h>\n")
	b.WriteString("#define IOTM_ASSET_ATTR PROGMEM\n")
	b.WriteString("#define iotm_asset_read(arr, i) pgm_read_byte(&(arr)[(i)])\n")
	b.WriteString("#else\n")
	b.WriteString("#define IOTM_ASSET_ATTR\n")
	b.WriteString("#define iotm_asset_read(arr, i) ((arr)[(i)])\n")
	b.WriteString("#endif\n")
	b.WriteString("#endif /* IOTM_ASSET_HELPERS */\n\n")
	fmt.Fprintf(&b, "static const unsigned char %s[] IOTM_ASSET_ATTR = {", sym)
	for i, by := range data {
		if i%12 == 0 {
			b.WriteString("\n    ")
		} else {
			b.WriteByte(' ')
		}
		fmt.Fprintf(&b, "0x%02x,", by)
	}
	if len(data) > 0 {
		b.WriteByte('\n')
	}
	b.WriteString("};\n")
	// unsigned long, NOT unsigned int: C99 guarantees long >= 32 bits on
	// every target, while int is 16 on AVR — an asset past 64 KB would
	// silently truncate its length there. No include needed, stays
	// self-contained. Português: unsigned long, NÃO unsigned int: C99
	// garante long >= 32 bits em todo alvo; int é 16 no AVR e um asset
	// acima de 64 KB truncaria o tamanho em silêncio. Sem include,
	// autocontido.
	fmt.Fprintf(&b, "static const unsigned long %s_len = %dul;\n\n", sym, len(data))
	fmt.Fprintf(&b, "#endif /* %s */\n", guard)
	return []byte(b.String())
}
