// server/projectexport/asset_headers_test.go
//
// SPDX-FileCopyrightText: 2026 Helmut Kemper
// SPDX-License-Identifier: AGPL-3.0-only

package projectexport

import (
	"strings"
	"testing"
)

// The naming contract is the feature: the specialist hand-writes the
// #include and the symbol BEFORE any export exists, so these derivations
// must be boringly predictable and never change. Pin them.
//
// Português: O contrato de nomes É a feature — o especialista escreve o
// #include e o símbolo À MÃO antes do export existir; as derivações têm
// que ser previsíveis e imutáveis. Fixadas aqui.
func TestAssetHeaderPath_NamingContract(t *testing.T) {
	cases := map[string]string{
		"templates/logo.gif":   "templates/logo_gif_data.h",
		"logo.gif":             "logo_gif_data.h",
		"data/portal.html":     "data/portal_html_data.h",
		"a/b/c/notes.txt":      "a/b/c/notes_txt_data.h",
		"weird.name.with.dots": "weird_name_with_dots_data.h",
	}
	for in, want := range cases {
		if got := AssetHeaderPath(in); got != want {
			t.Errorf("AssetHeaderPath(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestRenderAssetHeader_SymbolGuardAndLen(t *testing.T) {
	data := []byte("GIF89a")
	out := string(RenderAssetHeader("templates/logo.gif", data))

	for _, needle := range []string{
		// Symbol stem: path-derived, lowercase, non-alnum → '_'.
		"static const unsigned char asset_templates_logo_gif[] = {",
		"static const unsigned int asset_templates_logo_gif_len = 6;",
		// Include guard from the same stem, uppercased.
		"#ifndef ASSET_TEMPLATES_LOGO_GIF_DATA_H",
		"#endif /* ASSET_TEMPLATES_LOGO_GIF_DATA_H */",
		// Provenance + do-not-edit, both languages.
		"Generated by IoTMaker from templates/logo.gif",
		"não edite",
		// The bytes themselves ('G' = 0x47).
		"0x47,",
	} {
		if !strings.Contains(out, needle) {
			t.Errorf("header missing %q:\n%s", needle, out)
		}
	}
}

// xxd -i convention: 12 bytes per line — embedded folk diff these files;
// a drifting line width churns every diff for nothing.
func TestRenderAssetHeader_TwelvePerLine(t *testing.T) {
	out := string(RenderAssetHeader("x.txt", make([]byte, 30)))
	var counts []int
	for _, line := range strings.Split(out, "\n") {
		if n := strings.Count(line, "0x"); n > 0 {
			counts = append(counts, n)
		}
	}
	want := []int{12, 12, 6}
	if len(counts) != len(want) {
		t.Fatalf("byte lines: got %v, want %v", counts, want)
	}
	for i := range want {
		if counts[i] != want[i] {
			t.Fatalf("byte lines: got %v, want %v", counts, want)
		}
	}
}

// Empty asset: still a valid header — zero-length array, len = 0, no
// stray blank byte line.
func TestRenderAssetHeader_Empty(t *testing.T) {
	out := string(RenderAssetHeader("empty.txt", nil))
	if !strings.Contains(out, "asset_empty_txt[] = {};") {
		t.Errorf("empty asset must render an empty array:\n%s", out)
	}
	if !strings.Contains(out, "asset_empty_txt_len = 0;") {
		t.Errorf("empty asset must render len = 0:\n%s", out)
	}
}
